// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using porganizer.Database;

#nullable disable

namespace porganizer.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260406102618_AddPrdbDownloadedFromIndexerSyncState")]
    partial class AddPrdbDownloadedFromIndexerSyncState
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("porganizer.Database.AppSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("IndexerRowMatchLastRunAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrdbActorLastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PrdbActorSyncPage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrdbActorTotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrdbApiKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbApiUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrdbWantedVideoLastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PreferredVideoQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrenamesBackfillPage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PrenamesBackfillTotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PrenamesSyncCursorUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SafeForWork")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SyncWorkerLastRunAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PrdbActorSyncPage = 1,
                            PrdbApiKey = "",
                            PrdbApiUrl = "https://api.prdb.net",
                            PreferredVideoQuality = 2,
                            SafeForWork = false
                        });
                });

            modelBuilder.Entity("porganizer.Database.DownloadClient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("ClientType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DownloadClients");
                });

            modelBuilder.Entity("porganizer.Database.DownloadLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClientItemId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadClientId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("DownloadedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerRowId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastPolledAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("MissedPollCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NzbName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NzbUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrdbDownloadedFromIndexerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrdbDownloadedFromIndexerSyncAttemptedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbDownloadedFromIndexerSyncError")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrdbDownloadedFromIndexerSyncFingerprint")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrdbDownloadedFromIndexerSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long?>("TotalSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadClientId");

                    b.HasIndex("IndexerRowId");

                    b.ToTable("DownloadLogs");
                });

            modelBuilder.Entity("porganizer.Database.DownloadLogFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DownloadLogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OsHash")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("PHash")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrdbDownloadedFromIndexerFilenameId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadLogId");

                    b.ToTable("DownloadLogFiles");
                });

            modelBuilder.Entity("porganizer.Database.FolderMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MappedToFolder")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalFolder")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MappedToFolder")
                        .IsUnique();

                    b.HasIndex("OriginalFolder")
                        .IsUnique();

                    b.ToTable("FolderMappings");
                });

            modelBuilder.Entity("porganizer.Database.Indexer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BackfillCompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BackfillCurrentOffset")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BackfillCutoffUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackfillDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BackfillLastRunAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("BackfillStartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParsingType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Indexers");
                });

            modelBuilder.Entity("porganizer.Database.IndexerApiRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ResponseTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IndexerId");

                    b.ToTable("IndexerApiRequests");
                });

            modelBuilder.Entity("porganizer.Database.IndexerRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("IndexerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NzbId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("NzbPublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("NzbSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NzbUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndexerId");

                    b.ToTable("IndexerRows");
                });

            modelBuilder.Entity("porganizer.Database.IndexerRowMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IndexerRowId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("MatchedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("MatchedPreDbEntryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedTitle")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PrdbVideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IndexerRowId")
                        .IsUnique();

                    b.HasIndex("MatchedPreDbEntryId");

                    b.HasIndex("PrdbVideoId");

                    b.ToTable("IndexerRowMatches");
                });

            modelBuilder.Entity("porganizer.Database.PrdbActor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<int?>("BirthdayType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthplace")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BraSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BraSizeLabel")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("BreastType")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CareerEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CareerStart")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("Deathday")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Ethnicity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Eyecolor")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FavoritedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Haircolor")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HipSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Nationality")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Piercings")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrdbCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrdbUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tattoos")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("WaistSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("PrdbActors");
                });

            modelBuilder.Entity("porganizer.Database.PrdbActorAlias", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("PrdbActorAliases");
                });

            modelBuilder.Entity("porganizer.Database.PrdbActorImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ImageType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ActorId");

                    b.ToTable("PrdbActorImages");
                });

            modelBuilder.Entity("porganizer.Database.PrdbNetwork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PrdbNetworks");
                });

            modelBuilder.Entity("porganizer.Database.PrdbPreDbEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrdbSiteId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("PrdbVideoId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("SiteTitle")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VideoTitle")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("PrdbSiteId");

                    b.HasIndex("PrdbVideoId");

                    b.HasIndex("Title");

                    b.ToTable("PrdbPreDbEntries");
                });

            modelBuilder.Entity("porganizer.Database.PrdbSite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FavoritedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("NetworkId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NetworkId");

                    b.ToTable("PrdbSites");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DetailSyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrdbCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrdbUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SiteId");

                    b.ToTable("PrdbVideos");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideoActor", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("PrdbVideoActors");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideoImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CdnPath")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.ToTable("PrdbVideoImages");
                });

            modelBuilder.Entity("porganizer.Database.PrdbWantedVideo", b =>
                {
                    b.Property<Guid>("VideoId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FulfilledAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FulfilledInQuality")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FulfillmentByApp")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FulfillmentExternalId")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFulfilled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PrdbCreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PrdbUpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoId");

                    b.ToTable("PrdbWantedVideos");
                });

            modelBuilder.Entity("porganizer.Database.DownloadLog", b =>
                {
                    b.HasOne("porganizer.Database.DownloadClient", "DownloadClient")
                        .WithMany()
                        .HasForeignKey("DownloadClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("porganizer.Database.IndexerRow", "IndexerRow")
                        .WithMany()
                        .HasForeignKey("IndexerRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownloadClient");

                    b.Navigation("IndexerRow");
                });

            modelBuilder.Entity("porganizer.Database.DownloadLogFile", b =>
                {
                    b.HasOne("porganizer.Database.DownloadLog", "DownloadLog")
                        .WithMany("Files")
                        .HasForeignKey("DownloadLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DownloadLog");
                });

            modelBuilder.Entity("porganizer.Database.IndexerApiRequest", b =>
                {
                    b.HasOne("porganizer.Database.Indexer", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");
                });

            modelBuilder.Entity("porganizer.Database.IndexerRow", b =>
                {
                    b.HasOne("porganizer.Database.Indexer", "Indexer")
                        .WithMany()
                        .HasForeignKey("IndexerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Indexer");
                });

            modelBuilder.Entity("porganizer.Database.IndexerRowMatch", b =>
                {
                    b.HasOne("porganizer.Database.IndexerRow", "IndexerRow")
                        .WithMany()
                        .HasForeignKey("IndexerRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("porganizer.Database.PrdbPreDbEntry", "MatchedPreDbEntry")
                        .WithMany()
                        .HasForeignKey("MatchedPreDbEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("porganizer.Database.PrdbVideo", "Video")
                        .WithMany()
                        .HasForeignKey("PrdbVideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IndexerRow");

                    b.Navigation("MatchedPreDbEntry");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("porganizer.Database.PrdbActorAlias", b =>
                {
                    b.HasOne("porganizer.Database.PrdbActor", "Actor")
                        .WithMany("Aliases")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("porganizer.Database.PrdbActorImage", b =>
                {
                    b.HasOne("porganizer.Database.PrdbActor", "Actor")
                        .WithMany("Images")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");
                });

            modelBuilder.Entity("porganizer.Database.PrdbPreDbEntry", b =>
                {
                    b.HasOne("porganizer.Database.PrdbSite", "Site")
                        .WithMany("PreDbEntries")
                        .HasForeignKey("PrdbSiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("porganizer.Database.PrdbVideo", "Video")
                        .WithMany("PreDbEntries")
                        .HasForeignKey("PrdbVideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Site");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("porganizer.Database.PrdbSite", b =>
                {
                    b.HasOne("porganizer.Database.PrdbNetwork", "Network")
                        .WithMany("Sites")
                        .HasForeignKey("NetworkId");

                    b.Navigation("Network");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideo", b =>
                {
                    b.HasOne("porganizer.Database.PrdbSite", "Site")
                        .WithMany("Videos")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideoActor", b =>
                {
                    b.HasOne("porganizer.Database.PrdbActor", "Actor")
                        .WithMany("VideoActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("porganizer.Database.PrdbVideo", "Video")
                        .WithMany("VideoActors")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideoImage", b =>
                {
                    b.HasOne("porganizer.Database.PrdbVideo", "Video")
                        .WithMany("Images")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("porganizer.Database.PrdbWantedVideo", b =>
                {
                    b.HasOne("porganizer.Database.PrdbVideo", "Video")
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");
                });

            modelBuilder.Entity("porganizer.Database.DownloadLog", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("porganizer.Database.PrdbActor", b =>
                {
                    b.Navigation("Aliases");

                    b.Navigation("Images");

                    b.Navigation("VideoActors");
                });

            modelBuilder.Entity("porganizer.Database.PrdbNetwork", b =>
                {
                    b.Navigation("Sites");
                });

            modelBuilder.Entity("porganizer.Database.PrdbSite", b =>
                {
                    b.Navigation("PreDbEntries");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("porganizer.Database.PrdbVideo", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("PreDbEntries");

                    b.Navigation("VideoActors");
                });
#pragma warning restore 612, 618
        }
    }
}
